# Generated by Django 3.0 on 2021-12-07 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=256)),
                ('director_signature', models.FileField(blank=True, null=True, upload_to='DirectorSignature/')),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=256)),
                ('registration_no', models.CharField(max_length=50)),
                ('fund_description', models.TextField()),
                ('supervisor_approval', models.BooleanField(default=False)),
                ('manager_approval', models.BooleanField(default=False)),
                ('fund_type', models.IntegerField(choices=[(0, 'Regulated'), (1, 'Unregulated')], default=0)),
                ('fund_manager_entity', models.CharField(blank=True, max_length=256, null=True)),
                ('fund_structure', models.IntegerField(choices=[(0, 'Open-End'), (1, 'Closed-End')], default=0)),
                ('offer_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('issued_shares', models.IntegerField(default=1)),
                ('ordinary_shares', models.IntegerField(default=1)),
                ('fund_status', models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Open'), (2, 'Funded'), (3, 'Re-fund'), (4, 'Frozen'), (5, 'Unfrozen'), (6, 'Close'), (7, 'Extend Term')], default=0)),
                ('reason_to_change', models.TextField(blank=True)),
                ('fund_size', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('lock_up_period', models.IntegerField(default=0, help_text='Time in years')),
                ('fund_year_end', models.IntegerField(choices=[(0, 'Jan'), (1, 'Feb'), (2, 'Mar'), (3, 'Apr'), (4, 'May'), (5, 'Jun'), (6, 'Jul'), (7, 'Aug'), (8, 'Sep'), (9, 'Oct'), (10, 'Nov'), (11, 'Dec')], default=11)),
                ('fund_end_date', models.DateField()),
                ('catch_up', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('legal_counsel', models.CharField(blank=True, max_length=256)),
                ('legal_counsel_rep', models.CharField(blank=True, max_length=256)),
                ('Auditor', models.CharField(blank=True, max_length=256)),
                ('Auditor_rep', models.CharField(blank=True, max_length=256)),
                ('Custodian', models.CharField(blank=True, max_length=256)),
                ('Custodian_rep', models.CharField(blank=True, max_length=256)),
                ('asset_under_management', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('FundAdministrator', models.CharField(max_length=256)),
                ('GIIN', models.CharField(max_length=50)),
                ('Preparer', models.CharField(blank=True, max_length=256, null=True)),
                ('Subscription_Agreement', models.FileField(upload_to='subscription_agreement/')),
                ('Investment_Agreement', models.FileField(upload_to='investment_agreement/')),
                ('PPM', models.FileField(upload_to='ppm/')),
                ('Director_Fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('Management_Fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('Hurdle_Rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('CTC', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('BankAccount', models.PositiveIntegerField()),
                ('BankAccessID', models.CharField(max_length=50)),
                ('BankAccessPassword', models.CharField(max_length=50)),
                ('Approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approve', to='core.Director')),
                ('AuthorizedSignatory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_sign', to='core.Director')),
                ('Bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='FundCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ReclassificationFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclassification_frequency_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_frequency_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(max_length=256)),
                ('subscriber_commitment', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='FundLife_Open',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundlife', models.PositiveIntegerField()),
                ('Board_Extension', models.PositiveIntegerField()),
                ('Investor_Extension', models.PositiveIntegerField()),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='FundLife_Close',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundlife', models.PositiveIntegerField()),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Fund')),
            ],
        ),
        migrations.AddField(
            model_name='fund',
            name='ReclassificationFrequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ReclassificationFrequency'),
        ),
        migrations.AddField(
            model_name='fund',
            name='directors',
            field=models.ManyToManyField(related_name='directors_all', to='core.Director'),
        ),
        migrations.AddField(
            model_name='fund',
            name='domicile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.FundCountry'),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_manager_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_manager_representator', to='core.Director'),
        ),
        migrations.AddField(
            model_name='fund',
            name='investment_committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_committ', to='core.Director'),
        ),
        migrations.AddField(
            model_name='fund',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ProductType'),
        ),
        migrations.AddField(
            model_name='fund',
            name='report_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ReportingCurrency'),
        ),
        migrations.AddField(
            model_name='fund',
            name='reporting_frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ReportingFrequency'),
        ),
        migrations.AddField(
            model_name='fund',
            name='sub_fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfund', to='core.Fund'),
        ),
        migrations.CreateModel(
            name='closingperiod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_Date', models.DateField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='BoardResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_resolution', models.FileField(blank=True, null=True, upload_to='board_resolution/')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fund')),
            ],
        ),
    ]
