# Generated by Django 3.0 on 2021-12-07 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211208_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_manager_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_manager_representator', to='core.Director'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='investment_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_committ', to='core.Director'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='reporting_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ReportingFrequency'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='sub_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfund', to='core.Fund'),
        ),
    ]
