# Generated by Django 3.1.7 on 2021-12-22 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211221_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundlifeclose',
            name='fund',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundlife', to='core.fund'),
        ),
    ]
