# Generated by Django 3.0 on 2021-12-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211208_0138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FundLife_Close',
            new_name='FundLifeClose',
        ),
        migrations.RenameModel(
            old_name='FundLife_Open',
            new_name='FundLifeOpen',
        ),
    ]
