# Generated by Django 3.0 on 2021-12-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211208_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='liquidate',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='fund',
            name='liquidateReason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='redeem',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='fund',
            name='redeemReason',
            field=models.TextField(blank=True),
        ),
    ]
