# Generated by Django 3.1.7 on 2021-12-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211223_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardresolution',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardResolution', to='core.fund'),
        ),
        migrations.AlterField(
            model_name='closingperiod',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closingDates', to='core.fund'),
        ),
    ]
