# Generated by Django 3.1.7 on 2021-12-22 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211223_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='core.fund'),
        ),
    ]
