# Generated by Django 3.0 on 2021-12-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211209_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='directors',
            field=models.ManyToManyField(null=True, related_name='directors_all', to='core.Director'),
        ),
    ]
