# Generated by Django 3.0 on 2021-12-09 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211210_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fund',
            name='directors',
            field=models.ManyToManyField(related_name='directors_all', to='core.Director'),
        ),
    ]
