# Generated by Django 3.0 on 2021-12-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211210_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='fund_manager_entity',
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_manager_entity',
            field=models.ManyToManyField(related_name='fund_manager_et', to='core.Director'),
        ),
        migrations.RemoveField(
            model_name='fund',
            name='fund_manager_rep',
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_manager_rep',
            field=models.ManyToManyField(related_name='fund_manager_representator', to='core.Director'),
        ),
    ]
