# Generated by Django 3.0 on 2021-12-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211212_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='manager_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='supervisor_reason',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='fund',
            name='fund_manager_entity',
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_manager_entity',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.RemoveField(
            model_name='fund',
            name='fund_manager_rep',
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_manager_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_manager_representator', to='core.Director'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='manager_approval',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1),
        ),
        migrations.AlterField(
            model_name='fund',
            name='supervisor_approval',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1),
        ),
    ]
