# Generated by Django 3.0 on 2021-12-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211214_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='investment_committee',
        ),
        migrations.AddField(
            model_name='fund',
            name='investment_committee',
            field=models.ManyToManyField(related_name='investment_committ', to='core.Director'),
        ),
    ]
